[distrobox]
name = "privbox"
image = "ghcr.io/gablank/box-priv:latest"
home = "${HOME}/distrobox/privbox/home"
replace = true
pull = true
start_now = true
init = false
root = true
unshare_netns = true
pre_init_hooks = "export SHELL=/usr/bin/zsh"
init_hooks = 'su - ${container_user_name} -c "bash /usr/local/share/box-init/init-user.sh" && rm -f /var/run/tailscale/tailscaled.sock && tailscaled --statedir=/var/lib/tailscale &'
additional_flags = "--security-opt seccomp=unconfined --device /dev/net/tun --cap-add NET_ADMIN --cap-add NET_RAW"

# Directories — auto-created on host by "box assemble", emitted as volume= lines
[[mount-dir]]
host = "${HOME}/distrobox/privbox/tailscale"
container = "/var/lib/tailscale"
options = "rw,z"

# Files/sockets — must already exist, appended to additional_flags as --volume
[[mount-file]]
host = "${XDG_RUNTIME_DIR}/podman/podman.sock"
container = "/podman.sock"
options = "rw"
